In [1]:
from jao import JaoPublicationToolPandasClient
from dotenv import load_dotenv
import os
import pandas as pd

In [2]:
load_dotenv()
jao_api_key = os.getenv("JAO_API_KEY")

client = JaoPublicationToolPandasClient(api_key=jao_api_key)

day = pd.Timestamp("20260801", tz="Europe/Warsaw")
start = pd.Timestamp("20260701", tz="Europe/Warsaw")
end = pd.Timestamp("20260802", tz="Europe/Warsaw")

# JAO - Joint Allocation Office

The Joint Allocation Office (JAO) is a centralized service company and Europe's Single Allocation Platform that auctions cross-border electricity transmission capacity rights on behalf of transmission system operators (TSOs)

## Description of Data from the JAO API
The following table provides an overview of the main variables obtained from the JAO API. The selection and terminology are based primarily on the official [CORE DA Publication Handbook](https://publicationtool.jao.eu/PublicationHandbook/Core_PublicationTool_Handbook_v2.2.pdf)

| Data | API Method Name | Unit | Market Time Unit (MTU) |
|---|---|---|---|
| Max Net Positions | `query_minmax_np` | MW | 1 hour |
| Max Exchanges (Maxbex) | `query_maxbex` | MW | 1 hour |
| Allocation Constraint | `query_allocationconstraint` | MW | 15 min |
| DC2F | `query_dc2f`| MW | 1 hour |

### 1. Max Net Positions

**Description:**

Minimum and maximum Core net positions in MW of each hub for each MTU of the day. These indicators are extracted from the final flow-based domain and final bilateral exchange restriction.

**Publication time:** 

10:30 am (D-1)

In [3]:
minmax_np = client.query_minmax_np(day=day)
minmax_np[[x for x in minmax_np.columns if "PL" in x]]

,minPL,minPL_LT_BigHub,minPL_SE4_SwePol,maxPL,maxPL_LT_BigHub,maxPL_SE4_SwePol
mtu,,,,,,
2026-08-01 00:00:00+02:00,-7181,-250,-491,7060,250,491
2026-08-01 01:00:00+02:00,-7210,-250,-491,7102,250,491
2026-08-01 02:00:00+02:00,-7233,-250,-491,7083,250,491
2026-08-01 03:00:00+02:00,-7122,-250,-491,6849,250,491
2026-08-01 04:00:00+02:00,-7121,-250,-491,6836,250,491
2026-08-01 05:00:00+02:00,-7175,-250,-491,6861,250,491
2026-08-01 06:00:00+02:00,-7212,-250,-491,6948,250,491
2026-08-01 07:00:00+02:00,-6929,-250,-491,6689,250,491
2026-08-01 08:00:00+02:00,-7024,-250,-491,6560,250,491
2026-08-01 09:00:00+02:00,-6645,-250,-491,6830,250,491
2026-08-01 10:00:00+02:00,-6543,-250,-491,6820,250,491
2026-08-01 11:00:00+02:00,-6571,-250,-491,6690,250,491
2026-08-01 12:00:00+02:00,-6731,-250,-491,6565,250,491
2026-08-01 13:00:00+02:00,-6591,-250,-491,6689,250,491
2026-08-01 14:00:00+02:00,-6700,-250,-491,6622,250,491
2026-08-01 15:00:00+02:00,-6720,-250,-491,6499,250,491
2026-08-01 16:00:00+02:00,-6657,-250,-491,6545,250,491
2026-08-01 17:00:00+02:00,-6750,-250,-491,6510,250,491
2026-08-01 18:00:00+02:00,-6756,-250,-491,6901,250,491
2026-08-01 19:00:00+02:00,-6632,-250,-491,6799,250,491
2026-08-01 20:00:00+02:00,-6717,-250,-491,6770,250,491
2026-08-01 21:00:00+02:00,-6755,-250,-491,7045,250,491
2026-08-01 22:00:00+02:00,-7220,-250,-491,7118,250,491
2026-08-01 23:00:00+02:00,-7104,-250,-491,7005,250,491

### 2. Max Exchanges (Maxbex)

**Description:**

Maximum bilateral exchanges between two Core hubs with assumption that the other net positions are zero. These indicators are extracted from the final flow-based domain and final bilateral exchange restriction.

**Publication time:**

10:30 am (D-1)

In [4]:
maxbex = client.query_maxbex(day=day, from_zone="PL")
maxbex

,PL>AT,PL>BE,PL>CZ,PL>DE,PL>FR,PL>HR,PL>HU,PL>NL,PL>RO,PL>SI,PL>SK,PL>PL_LT_BigHub,PL>PL_SE4_SwePol,PL>LT_BigHub_PL,PL>SE4_SwePol_PL
mtu,,,,,,,,,,,,,,,
2026-08-01 00:00:00+02:00,3572.0,4571.0,3032.0,4811.0,4437.0,3474.0,3209.0,4669.0,2567.0,3004.0,2220.0,250.0,491.0,250.0,491.0
2026-08-01 01:00:00+02:00,3550.0,4556.0,3013.0,4766.0,4421.0,3451.0,3300.0,4645.0,2644.0,3319.0,2191.0,250.0,491.0,250.0,491.0
2026-08-01 02:00:00+02:00,3576.0,4550.0,3037.0,4749.0,4432.0,3476.0,3337.0,4635.0,2754.0,3467.0,2204.0,250.0,491.0,250.0,491.0
2026-08-01 03:00:00+02:00,3508.0,4483.0,2992.0,4718.0,4354.0,3412.0,3183.0,4579.0,2646.0,3376.0,2176.0,250.0,491.0,250.0,491.0
2026-08-01 04:00:00+02:00,3505.0,4447.0,2965.0,4683.0,4319.0,3383.0,3154.0,4542.0,2764.0,2951.0,2157.0,250.0,491.0,250.0,491.0
2026-08-01 05:00:00+02:00,3465.0,4428.0,2953.0,4655.0,4300.0,3368.0,3118.0,4522.0,2760.0,2838.0,2166.0,250.0,491.0,250.0,491.0
2026-08-01 06:00:00+02:00,3574.0,4537.0,3009.0,4749.0,4408.0,3447.0,3231.0,4622.0,3020.0,2850.0,2222.0,250.0,491.0,250.0,491.0
2026-08-01 07:00:00+02:00,3555.0,4380.0,2988.0,4770.0,3902.0,3431.0,3360.0,4604.0,2932.0,3111.0,2486.0,250.0,491.0,250.0,491.0
2026-08-01 08:00:00+02:00,3535.0,4022.0,2986.0,4777.0,3597.0,3453.0,3378.0,4309.0,3062.0,3444.0,2811.0,250.0,491.0,250.0,491.0
2026-08-01 09:00:00+02:00,3665.0,4257.0,3067.0,4935.0,3795.0,3418.0,3512.0,4568.0,3294.0,3570.0,3008.0,250.0,491.0,250.0,491.0
2026-08-01 10:00:00+02:00,3628.0,4483.0,3051.0,4931.0,3795.0,3585.0,3514.0,4827.0,3688.0,3573.0,3031.0,250.0,491.0,250.0,491.0
2026-08-01 11:00:00+02:00,3387.0,4353.0,2821.0,4596.0,3696.0,3348.0,3281.0,4509.0,3443.0,3336.0,2766.0,250.0,491.0,250.0,491.0
2026-08-01 12:00:00+02:00,3367.0,4436.0,2825.0,4620.0,4295.0,3359.0,3290.0,4534.0,3412.0,3346.0,2601.0,250.0,491.0,250.0,491.0
2026-08-01 13:00:00+02:00,3310.0,4362.0,2778.0,4547.0,4223.0,3302.0,3235.0,4459.0,3395.0,3289.0,2658.0,250.0,491.0,250.0,491.0
2026-08-01 14:00:00+02:00,3297.0,4344.0,2769.0,4540.0,4206.0,3289.0,3223.0,4441.0,3382.0,3107.0,2539.0,250.0,491.0,250.0,491.0
2026-08-01 15:00:00+02:00,3236.0,4231.0,2691.0,4423.0,4096.0,3199.0,3134.0,4324.0,3289.0,3186.0,2725.0,250.0,491.0,250.0,491.0
2026-08-01 16:00:00+02:00,3204.0,4180.0,2704.0,4373.0,4048.0,3167.0,3105.0,4270.0,3115.0,3156.0,2565.0,250.0,491.0,250.0,491.0
2026-08-01 17:00:00+02:00,3062.0,3937.0,2582.0,4133.0,3820.0,2650.0,2927.0,4023.0,2934.0,2248.0,2114.0,250.0,491.0,250.0,491.0
2026-08-01 18:00:00+02:00,3141.0,4065.0,2663.0,4304.0,3943.0,2537.0,2995.0,4158.0,2719.0,2142.0,2212.0,250.0,491.0,250.0,491.0
2026-08-01 19:00:00+02:00,3268.0,4228.0,2784.0,4429.0,4100.0,2458.0,3117.0,4320.0,2796.0,2009.0,2255.0,250.0,491.0,250.0,491.0
2026-08-01 20:00:00+02:00,3349.0,4386.0,2878.0,4587.0,4248.0,2510.0,3199.0,4486.0,2808.0,1939.0,2343.0,250.0,491.0,250.0,491.0
2026-08-01 21:00:00+02:00,3564.0,4620.0,3034.0,4839.0,4475.0,2926.0,3353.0,4725.0,2996.0,2327.0,2425.0,250.0,491.0,250.0,491.0
2026-08-01 22:00:00+02:00,3677.0,4763.0,3122.0,4988.0,4614.0,3475.0,3454.0,4871.0,3022.0,2684.0,2281.0,250.0,491.0,250.0,491.0
2026-08-01 23:00:00+02:00,3653.0,4727.0,3119.0,4956.0,4579.0,3543.0,3337.0,4833.0,2945.0,2885.0,2240.0,250.0,491.0,250.0,491.0

### 3. Allocation Constraints 

**Description:**

As per the Core CCM, Belgium, Poland and the Netherlands are allowed to use external constraints.

**Publication time:**

10:30 am (D-1)

In [5]:
allocationconstraints = client.query_allocationconstraint(d_from=start, d_to=end)
allocationconstraints_pl = allocationconstraints[
    [x for x in allocationconstraints.columns if "PL" in x]
]
allocationconstraints_pl

                           PL_import  PL_export
mtu
2026-07-01 00:00:00+02:00       4491       1772
2026-07-01 00:15:00+02:00       4277       2024
2026-07-01 00:30:00+02:00       4130       2206
2026-07-01 00:45:00+02:00       3932       2446
2026-07-01 01:00:00+02:00       3885       2525
...                              ...        ...
2026-08-01 22:45:00+02:00       4560       1663
2026-08-01 23:00:00+02:00       4222       2049
2026-08-01 23:15:00+02:00       3865       2451
2026-08-01 23:30:00+02:00       3568       2787
2026-08-01 23:45:00+02:00       3326       3063

[3072 rows x 2 columns]

### 4. DC2F

**Description:**

Publishes the aggregated assumptions from the grid models for each MTU on TSU and Hub level: Vertical load, generation(production) and net position for each Core hub and TSO if it differs from the hub level
- “Vertical load” is the load as seen from the transmission grid in MW in the Common Grid Model
- “Generation” is the generation in MW in the Common Grid Model
- “Core net position” is the forecast of the overall balance of the countries in MW in the Common Grid Model

**Publication time:**

10:30 am (D-1)

In [ ]:
dc2f = client.query_d2cf(d_from=start, d_to=end)
dc2f

,verticalLoad_AT,verticalLoad_BE,verticalLoad_CZ,verticalLoad_DE,verticalLoad_FR,verticalLoad_HR,verticalLoad_HU,verticalLoad_NL,verticalLoad_PL,verticalLoad_RO,...,generation_50Hertz,generation_Amprion,generation_Creos,generation_TennetGmbh,generation_Transnet,coreNetPosition_50Hertz,coreNetPosition_Amprion,coreNetPosition_Creos,coreNetPosition_TennetGmbh,coreNetPosition_Transnet
mtu,,,,,,,,,,,,,,,,,,,,,
2026-07-01 00:00:00+02:00,6066,6678,5602,25720,36151,2267,5293,9277,17462,5795,...,4406,8320,0,1760,1562,389,-3795,-431,-3971,-3071
2026-07-01 01:00:00+02:00,5734,6384,5449,24928,34045,1863,4952,9155,16832,5620,...,3750,8300,0,1861,1299,-278,-3348,-405,-3508,-2975
2026-07-01 02:00:00+02:00,5892,6302,5297,24826,32374,1775,4911,9616,16852,5601,...,3718,8436,0,2028,1122,-183,-3356,-392,-3546,-2853
2026-07-01 03:00:00+02:00,5306,6439,5268,25961,30758,1759,4776,9592,16270,5620,...,3819,8718,0,2296,1225,-143,-3254,-388,-3946,-2863
2026-07-01 04:00:00+02:00,5532,6483,5356,27278,30330,1741,4817,9441,16043,5686,...,4256,8637,0,2215,1268,292,-3863,-397,-4430,-3123
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-08-01 19:00:00+02:00,5955,5409,4449,21750,33076,2668,5938,4643,15481,6601,...,6177,5013,0,2156,2031,3407,-2556,-357,-3814,-2382
2026-08-01 20:00:00+02:00,5824,6171,4350,24012,33832,2638,5904,6076,16672,6637,...,6332,4946,0,1941,2380,3040,-3034,-407,-4565,-2714
2026-08-01 21:00:00+02:00,5636,6306,4236,23581,32657,2553,5885,5895,16709,6287,...,6325,5130,0,1764,2158,2742,-3100,-420,-4249,-2668
2026-08-01 22:00:00+02:00,5638,5950,4412,23164,33354,2407,5837,5802,16019,5698,...,6592,5387,0,1709,2119,3066,-2531,-422,-4382,-2560
2026-08-01 23:00:00+02:00,5164,5431,3851,21179,32154,2194,5617,5500,14675,5372,...,6600,5379,0,1675,2141,3105,-1961,-399,-3178,-2429

In [7]:
dc2f.columns

Index(['verticalLoad_AT', 'verticalLoad_BE', 'verticalLoad_CZ',
       'verticalLoad_DE', 'verticalLoad_FR', 'verticalLoad_HR',
       'verticalLoad_HU', 'verticalLoad_NL', 'verticalLoad_PL',
       'verticalLoad_RO', 'verticalLoad_SI', 'verticalLoad_SK',
       'generation_AT', 'generation_BE', 'generation_CZ', 'generation_DE',
       'generation_FR', 'generation_HR', 'generation_HU', 'generation_NL',
       'generation_PL', 'generation_RO', 'generation_SI', 'generation_SK',
       'coreNetPosition_AT', 'coreNetPosition_BE', 'coreNetPosition_CZ',
       'coreNetPosition_DE', 'coreNetPosition_FR', 'coreNetPosition_HR',
       'coreNetPosition_HU', 'coreNetPosition_NL', 'coreNetPosition_PL',
       'coreNetPosition_RO', 'coreNetPosition_SI', 'coreNetPosition_SK',
       'verticalLoad_50Hertz', 'verticalLoad_Amprion', 'verticalLoad_Creos',
       'verticalLoad_TennetGmbh', 'verticalLoad_Transnet',
       'generation_50Hertz', 'generation_Amprion', 'generation_Creos',
       'generation_TennetGmbh', 'generation_Transnet',
       'coreNetPosition_50Hertz', 'coreNetPosition_Amprion',
       'coreNetPosition_Creos', 'coreNetPosition_TennetGmbh',
       'coreNetPosition_Transnet'],
      dtype='str')